### ISSUE TITLE
Illegal character constant causes crash

### ISSUE THREAD

**Issue by colossoi** [cout970/Elm-interpreter#1]
I was playing around with the repl, and found if you try an illegal char literal like `'asdf'`, it crashes.   I found that I could reproduce it with a simple test case:

```
diff --git a/src/parsers/expression.rs b/src/parsers/expression.rs
index bef2eec..343dabb 100644
--- a/src/parsers/expression.rs
+++ b/src/parsers/expression.rs
@@ -332,6 +332,7 @@ mod tests {
 
     #[test]
     fn expr_error_test() {
+        test_parser_error(parse_expr, "'as'");
         test_parser_error(parse_expr, "123.123.1");
         test_parser_error(parse_expr, "if 1 then 2");
         test_parser_error(parse_expr, "(");

```

And I think I traced the problem to this line of code in tokenizer/mod.rs:

`let new_pos = self.code.len() - input.len();
`

At this point in the code, `self.code.len()` is the "adjusted" code length ignoring ithe null padding at the end, and in this error case, `input.len()` is the unadjusted input length.  But I'm not sure what the best way to fix it is.

**Comment by cout970** [comment]
For now I will fix this issue, but I plan to replace the parsers with a new and more efficient design.

**Comment by colossoi** [comment]
Ok, thanks.  I'm interested in what you plan to replace it with.  I actually found your project by following the link on the nom page.  What problems do you have with the current implementation?

**Comment by cout970** [comment]
I first implemented the parsers with nom, but it was really hard generate relevant error messages.
So I made my own implementation, leaving nom only for the tokenizer. The problem is that it cannot recover from an error, if you have a typo, the hole module fails with only 1 error and ignores the rest.
 
Also the current implementation uses an immutable data structure for the parsing context and the bechmarks show that using Rc/Arc in this usecase hurts performance a lot, it's still very fast but using a mutable implementation it gets 10x faster.

**Comment by colossoi** [comment]
Is there any way I could help out with this project?  I'm specifically
interested in the rust interop.  I looked into it a bit and got stuck
understanding the def_register macro.

What are the barriers to getting the interop working, and is there anything
I could do to help?

Sorry to hijack this thread, I couldn't find good contact info for  you or
the project anywhere.

**Comment by cout970** [comment]
Do you have a discord account? https://discord.gg/k8PKnk
Also help would be appreciated, right now I'm in the process of rewriting the type inference engine and I'm very close to have the elm-core fully working.
The def_register macro was copied from other [project](https://github.com/jonathandturner/rhai/blob/master/src/fn_register.rs), but basically it implements a trait for all combinations of arguments.
